{
 "title": "Configuration",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Yellow threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"co2monitors\")\r\n//  |> range(start: -1y)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"configuration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"yellowThreshold\")\r\n  |> last()\r\n  |> map(fn:  (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with dev_id: \r\n      if r.dev_id == \"10\" then \"Room x\" \r\n      else r.dev_id }))"
    }
   ]
  },
  {
   "title": "Red threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"co2monitors\")\r\n//  |> range(start: -1y)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"configuration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"redThreshold\")\r\n  |> last()\r\n  |> map(fn:  (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with dev_id: \r\n      if r.dev_id == \"10\" then \"Room x\" \r\n      else r.dev_id }))"
    }
   ]
  },
  {
   "title": "Dark red threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"co2monitors\")\r\n//  |> range(start: -1y)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"configuration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"darkRedThreshold\")\r\n  |> last()\r\n  |> map(fn:  (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with dev_id: \r\n      if r.dev_id == \"10\" then \"Room x\" \r\n      else r.dev_id }))"
    }
   ]
  },
  {
   "title": "Brightness PWM",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"co2monitors\")\r\n//  |> range(start: -1y)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"configuration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"brightness\")\r\n  |> last()\r\n  |> map(fn:  (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with dev_id: \r\n      if r.dev_id == \"10\" then \"Room x\" \r\n      else r.dev_id }))"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"co2monitors\")\r\n//  |> range(start: -1y)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"configuration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"altitude\")\r\n  |> last()\r\n  |> map(fn:  (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with dev_id: \r\n      if r.dev_id == \"10\" then \"Room x\" \r\n      else r.dev_id }))"
    }
   ]
  },
  {
   "title": "Temperature offset",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"co2monitors\")\r\n//  |> range(start: -1y)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"configuration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tempOffset\")\r\n  |> last()\r\n  |> map(fn:  (r) => ({ r with _field: \"\" }))\r\n  |> map(fn: (r) => ({ r with dev_id: \r\n      if r.dev_id == \"10\" then \"Room x\" \r\n      else r.dev_id }))"
    }
   ]
  },
  {
   "title": "App version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"co2monitors\")\r\n//  |> range(start: -1y)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"configuration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"appVersion\")\r\n  |> last()\r\n  |> map(fn:  (r) => ({\"\":r._value, dev_id:r.dev_id}))\r\n  |> map(fn: (r) => ({ r with dev_id: \r\n      if r.dev_id == \"10\" then \"Room x\" \r\n      else r.dev_id }))"
    }
   ]
  },
  {
   "title": "Last measurement",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"co2monitors\")\r\n//  |> range(start: -1y)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\r\n  |> last()\r\n  |> map(fn:  (r) => ({\"\":r._time, dev_id:r.dev_id}))\r\n    |> map(fn: (r) => ({ r with \r\n    dev_id: \r\n      if r.dev_id == \"10\" then \"Room x\" \r\n      else r.dev_id }))"
    }
   ]
  },
  {
   "title": "Config refresh",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"co2monitors\")\r\n//  |> range(start: -1y)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"configuration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"appVersion\")\r\n  |> last()\r\n  |> map(fn:  (r) => ({\"\":r._time, dev_id:r.dev_id}))\r\n    |> map(fn: (r) => ({ r with \r\n    dev_id: \r\n      if r.dev_id == \"10\" then \"Room x\" \r\n      else r.dev_id }))"
    }
   ]
  },
  {
   "title": "Config refresh",
   "type": "stat",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"co2monitors\")\r\n//  |> range(start: -1y)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"configuration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"appVersion\")\r\n  |> last()\r\n  |> map(fn:  (r) => ({\"\":r._time, dev_id:r.dev_id}))\r\n    |> map(fn: (r) => ({ r with \r\n    dev_id: \r\n      if r.dev_id == \"10\" then \"Room x\" \r\n      else r.dev_id }))"
    }
   ]
  }
 ]
}