
#define LED_PIN                2
#define BUZZER_PIN             1
#define SD_DETECT              3
#define SD_DAT0                5
#define SD_DAT1                4
#define SD_DAT2                8
#define SD_DAT3               18
#define SD_CLK                 6
#define SD_CMD                 7
#define VBAT_ADC               9
#define BTN_1                  0
#define BTN_2                 12
#define BTN_3                 11
#define BTN_4                 10
#define OLED_EN               13
#define NEO_DATA              17
#define XTAL_32k_1            15
#define XTAL_32k_2            16
#define VBAT_EN               46
#define SDA_PIN               14
#define SCL_PIN               21
#define NEO_1_EN              48
#define NEO_23_EN             47